/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.nosknut.javarestapi;

import com.fasterxml.jackson.databind.node.ObjectNode;
import com.nosknut.javarestapi.embedhttp.JsonUtils;

import okhttp3.Response;

public class App {
    public static void main(String[] args) throws Exception {
        RestApi.init();

        try (Response response = RestClient.postByteString(
                "http://localhost:7070/files?filePath=testFiles/testPost.dat",
                FileUtils.readFileToByteString("testFiles/test.dat"))) {

        }

        ObjectNode json = JsonUtils.createJsonObject();
        json.put("field", "value");
        String body = FileUtils.encodeString(JsonUtils.serializeJson(json));
        try (Response response = RestClient.postByteString("http://localhost:7070/files?filePath=testFiles/json.json", body)) {

        }

        try (Response response = RestClient.get("http://localhost:7070/files?filePath=testFiles/json.json")) {
            String bodyString = response.body().string();
            FileUtils.writeByteStringToFile("testFiles/getJson.json", bodyString);
        }

        while (true) {
            Thread.sleep(1000);
        }
    }
}
