/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.nosknut.javarestapi;

public class App {
    public static void main(String[] args) throws Exception {
        RestApi.init();
        while (true) {
            Thread.sleep(1000);
        }
    }
}
